swiftmailer:
    url: 'gmail://davidlarrimore@lrespto.org@localhost'
    password: '%mailer_password%'
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

