twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        main_app_url: '%env(MAIN_APP_URL)%'  
    form_themes: ['bootstrap_4_layout.html.twig']        