language: php
php:
- '7.1'
branches:
  only:
  - test
  - master
cache:
  directories:
  - $HOME/.composer/cache/files
services:
- mysql
env:
- SYMFONY_VERSION="4.1.*" DB=mysql
before_script:
- cp app/config/parameters.yml.travis app/config/parameters.yml
- composer install
- php bin/console doctrine:database:create --env=dev
- php bin/console doctrine:schema:create --env=dev
- php bin/console hautelook:fixtures:load --env=dev --quiet
- php bin/console app:refresh-donation-db
notifications:
  slack:
    secure: DY68YgfJk5wb5pNBjjQtQ31nkD+ssBJdWcWXpniz7jO8lxkP16wotRKa5S/PHIejHfDb4H4d5J7UwEBmR6nOHopwIiazoLCrxfKSNq9s2iDFJ7cQh349fFkcx/7fDhQBIgzyFx8/JfQ2LAemL2ybEMq3kGsEtiIlv0iNZQ9GBZnZ8SdXGv1Ye2sbo7lV0Tml0x36vjvvZlIyLPQDo1MgrQyeiHJ/S/bMqVkliXBTsaCTm3OwayaYJ9x5EMGmcLzoyeBbbw4becV3eIQFMqO9AS/52j6QCKIHtE2PDUsBzW8UKGnUc1ZSd3ITKbgfdcwa5lFOIx1gNkzaMfNKjxBbS1lw5QiHdBXDyoNU6+yWJ+nFFcvBgwXadiTfkmrWjqYGBW7Dn7udHNB2c7dstWizNikdebrCz3dYAhCWUihF9EeJ1wJQsrZd5/6qMYymTuyjbktEinKJYpWP8aFAx9mPv5kV3U2W/UR4VXs0JoBniHH8uQzKQ2rNduttoVHSNw/unrNbRW8oAzKp+HPVk/4YSM130UxOORW6yA6jNyXwddxeZrXtC8WSfDaFCx4qRyQb0/NcJZ0mwp2NZgSReZcOUmPwRGXZ7JhL4X+0U61tOdGAWCxni9Bo3I5ZfUlkz0TIz3B95T1uDVqx/Ns8Q51I2+/Sqpo4LfQHDzvTt0HhOWM=
addons:
  sonarcloud:
    organization: frmanager-github
    token:
      secure: Bjsrh3XhyoR20aLpb0/JGsOhmDCHI2Wz5u2yLl5NFDIvu94xm1cKgfLSJXKya3SmHMEUaCVJ5mAzeDaMUc3y860X1hWwpsIBkXZV8O68KB8NKNkYjXFzbY5pZnAtUa1PQ8JcDZBM/b8WVWdEOK6f/6MZ1JvjvdzHh6RzNVi/4RIDYx0lODhRrYD9cBm5z0Q+2yxZIbGZz12nE0UcBnbf52Oxpwmu47mlSRkhIQYjIJrJSA1arh50U6EBlwS0CmauSSrfNE3rpmiApjkLHDXth8dSdICmiFCnBxEz1DGbJPSwXEZYGkL4U5CzkiWe+O+KZEUuo5XeruPA98Q0zaLpeO3dq5JpSRWplRBYEldKDiTCklPuS/Y1HRWj0G3d52o3m3gH+EjOpTNYfqCYx7cOFUVwhpghPTYPRb5DJ2sM1uZGwHQygcUP4WZe+k+ULao/3XegU5scAfeavWf87B9+ptrI1tpKJtZddFXuDqDcK4gNDparjSJVpxlMcvj/9eH7s8qSL7ivBf6wnhWelJAjbmPhtU9N5Ru0s25qoBhN2BOnhrKK8iqew/wGcF8+Qc0fajXRhIyaikw9p6aBMX0hEtCedfo6fPQ1im7jBTQP3zodN7fpDunpdSO2PG1x3h28U+P/gGRjKEyRbiXd3Iz2GudU+Y3+y26piPNNDJb6GYk=
    branches:
      - test
      - master
script:
- phpunit
- sonar-scanner
