language: php
php:
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE frmanager_test;'

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console hautelook:fixtures:load --env=test

script:
  - phpunit -c app

notifications:
  email:
    -  joinus@theodo.fr 😉
