# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            form_login:
                provider: our_db_provider
                login_path: /account/login
                check_path: /account/login
                default_target_path: loginRedirect
            logout:
                path: /account/logout
                target: homepage
            anonymous:    true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/account/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
