# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    app.CSVHelper:
        class: AppBundle\Utils\CSVHelper

    app.QueryHelper:
        class: AppBundle\Utils\QueryHelper
        arguments: ['@doctrine.orm.default_entity_manager', '@logger']

    app.ValidationHelper:
        class: AppBundle\Utils\ValidationHelper

    AppBundle\Controller\RegistrationController:
        class: AppBundle\Controller\RegistrationController
        autowire: true # or define your controller constructor and configure its arguments explicitly
        tags:
            - name: controller.service_arguments

    data_fixtures.provider.subtract:
        class: AppBundle\DataFixtures\Provider\EquationProvider
        tags: [ { name: nelmio_alice.faker.provider } ]
