parameters:
    app.alice.parameters.password: "$2y$13$JYCDsqtyOBKCSXSuncy2MONK9SqhHb2YPFr3rFzzNGLlrgZW2Gvby"
    app.alice.parameters.grades:
        - 'Kindergarten'
        - '1st Grade'
        - '2nd Grade'
        - '3rd Grade'
        - '4th Grade'
        - '5th Grade'
        - 'Special Eduation'
